[package]
name = "omarcoaraujo/rbxapi"
version = "0.1.1"
license = "MIT"
authors = ["Marco Antônio"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["aftman.toml", "**/*.json", "wally.lock", "tests"]

[dependencies]
Signal = "sleitnick/signal@2.0.3"