[package]
name = "omarcoaraujo/rbxapi"
version = "0.1.8"
license = "MIT"
authors = ["Marco Antônio"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["tests", "test.project.json"]

[dependencies]
Signal = "sleitnick/signal@2.0.3"